### ISSUE TITLE
Conclusão de Layouts

### ISSUE THREAD

**Issue by wandersonlira** [wandersonlira/Easy-Financing-App#29]
## :sparkles: Conclusão de Layout

> [!NOTE]
>  ### 1. Tipo de Layout utilizado?
>    - RelativeLayout
>    - ConstraintLayout
>
> ### 2. Quais componentes View foram usados?
>   - ImageButton
>   - View
>   - TextView
>   - ImageView
>   - ScrollView
>   - RecycleView
>
> ### 3. Outros componentes:
>     - com.google.android.material.floatingactionbutton.FloatingActionButton
>     - androidx.cardview.widget.CardView

> [!TIP]
> ### Autor
> @wandersonlira
> @RivysonClaudio

**Comment by RivysonClaudio** [comment]
Finalizado
